config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :items
  resources :dishes
  resources :restaurants do
    resources :items
    member do
      get "dishes"
    end
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dish.rb
class Dish < ApplicationRecord
    has_many :items

    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :dish
    
  belongs_to :restaurant

  validates :name, presence: true
  validates :price, presence: true
  validates :callories, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :items

    validates :name, presence: true
    validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show edit update destroy ]

  # GET /dishes or /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes or /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully created." }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully updated." }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url, notice: "Dish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.joins(:items).group(:id).order('COUNT(items.id) DESC').limit(3)

    end
  end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :callories, :restaurant_id, :dish_id)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @items = @restaurant.items.select(:id, :name, :price)
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def dishes
    @restaurant = Restaurant.find(params[:id])
    @dishes = @restaurant.dishes

    respond_to do |format|
      format.html { render partial: "dishes" }
    end
  end

  def search
    search_value = params[:search]
    @restaurants = Restaurant.where("name ILIKE ?", "%#{search_value}%")

    respond_to do |format|
      format.html { render partial: "restaurants/restaurant_list" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">
  <p>
    <strong>Name:</strong>
    <%= dish.name %>
  </p>

</div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |form| %>
  <% if dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Show this dish", @dish %> |
  <%= link_to "Back to dishes", dishes_path %>
</div>

app/views/dishes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dishes</h1>

<div id="dishes">
  <% @dishes.each do |dish| %>
    <%= render dish %>
    <p>
      <%= link_to "Show this dish", dish %>
    </p>
  <% end %>
</div>

<%= link_to "New dish", new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Back to dishes", dishes_path %>
</div>

app/views/dishes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dish %>

<div>
  <%= link_to "Edit this dish", edit_dish_path(@dish) %> |
  <%= link_to "Back to dishes", dishes_path %>

  <%= button_to "Destroy this dish", @dish, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Top Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h3><%= restaurant.name %></h3>
      <p>Address: <%= restaurant.address %></p>
      <p>Number of Items: <%= restaurant.items.count %></p>
      <%= link_to "See more", "#", class: "see-more-button", data: { restaurant_id: restaurant.id } %>
      <div class="dishes-container"></div>
    </li>
  <% end %>
</ul>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :callories, style: "display: block" %>
    <%= form.number_field :callories %>
  </div>

  <div>
    <%= form.label :restaurant_id, style: "display: block" %>
    <%= form.text_field :restaurant_id %>
  </div>

  <div>
    <%= form.label :dish_id, style: "display: block" %>
    <%= form.text_field :dish_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>

  <p>
    <strong>Callories:</strong>
    <%= item.callories %>
  </p>

  <p>
    <strong>Restaurant:</strong>
    <%= item.restaurant_id %>
  </p>

  <p>
    <strong>Dish:</strong>
    <%= item.dish_id %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= render 'shared/navbar' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_dishes.html.erb
<h4>All Dishes:</h4>

<ul>
  <% @dishes.each do |dish| %>
    <li><%= dish.name %></li>
  <% end %>
</ul>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

</div>

app/views/restaurants/_restaurant_list.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant.name %></li>
  <% end %>
</ul>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

<%= link_to "New restaurant", new_restaurant_path %>


<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant_path(restaurant) %>
<% end %>

<div id="restaurant-list">
  <!-- Render the initial list of restaurants

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @restaurant.name %></h1>
<%= render @restaurant %>


<h2>Items</h2>
<ul>
  <% @items.each do |item| %>
    <li>
      <%= item.name %>:  <%= item.price %> $
      <%= check_box_tag "selected_items[]", item.id, false, class: "item-checkbox", data: { price: item.price } %>
    </li>
  <% end %>
</ul>

<p>Total Price: <span id="total-price">0</span>$</p>
(the sum only works after reloading the page)




<script>
  document.addEventListener("DOMContentLoaded", () => {
  const checkboxes = document.querySelectorAll(".item-checkbox");
  const totalPriceElement = document.getElementById("total-price");
  let totalPrice = 0;
    // Reset checkboxes on page load
  checkboxes.forEach((checkbox) => {
    checkbox.checked = false;
  });

  checkboxes.forEach((checkbox) => {
    checkbox.addEventListener("change", () => {
      const checkedCheckboxes = document.querySelectorAll(".item-checkbox:checked");
      totalPrice = 0;

      checkedCheckboxes.forEach((checkedCheckbox) => {
        const itemPrice = parseInt(checkedCheckbox.dataset.price, 10);
        totalPrice += itemPrice;
      });

      totalPriceElement.innerText = totalPrice;
    });
  });
});
</script>

<div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>

  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Your Application</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Restaurants', restaurants_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Dishes', dishes_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Items', items_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <form class="form-inline my-2 my-lg-0" id="search-form">
          <input class="form-control mr-sm-2" type="search" placeholder="Search Restaurants" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </li>
    </ul>
  </div>
</nav>